// <auto-generated />
namespace PostExample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class CratedbandtblUsersandtblPosts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CratedbandtblUsersandtblPosts));
        
        string IMigrationMetadata.Id
        {
            get { return "202002111911063_Crate db and tblUsers and tblPosts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
