// <auto-generated />
namespace PostExample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Createtableposts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Createtableposts));
        
        string IMigrationMetadata.Id
        {
            get { return "202002121637429_Create table posts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
