// <auto-generated />
namespace PersonalsApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Adduserphotos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adduserphotos));
        
        string IMigrationMetadata.Id
        {
            get { return "202003101454466_Add userphotos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
